/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить PDF сметы для отображения
 */
export type generatePdfTableControllerGeneratePdfTableResponse200 = {
    data: void;
    status: 200;
};

export type generatePdfTableControllerGeneratePdfTableResponse404 = {
    data: void;
    status: 404;
};

export type generatePdfTableControllerGeneratePdfTableResponse500 = {
    data: void;
    status: 500;
};

export type generatePdfTableControllerGeneratePdfTableResponseSuccess =
    generatePdfTableControllerGeneratePdfTableResponse200 & {
        headers: Headers;
    };
export type generatePdfTableControllerGeneratePdfTableResponseError = (
    | generatePdfTableControllerGeneratePdfTableResponse404
    | generatePdfTableControllerGeneratePdfTableResponse500
) & {
    headers: Headers;
};

export type generatePdfTableControllerGeneratePdfTableResponse =
    | generatePdfTableControllerGeneratePdfTableResponseSuccess
    | generatePdfTableControllerGeneratePdfTableResponseError;

export const getGeneratePdfTableControllerGeneratePdfTableUrl = (
    id: string,
) => {
    return `/api/generate-pdf-table/${id}`;
};

export const generatePdfTableControllerGeneratePdfTable = async (
    id: string,
    options?: RequestInit,
): Promise<generatePdfTableControllerGeneratePdfTableResponse> => {
    return customInstance<generatePdfTableControllerGeneratePdfTableResponse>(
        getGeneratePdfTableControllerGeneratePdfTableUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGeneratePdfTableControllerGeneratePdfTableQueryKey = (
    id: string,
) => {
    return [`/api/generate-pdf-table/${id}`] as const;
};

export const getGeneratePdfTableControllerGeneratePdfTableQueryOptions = <
    TData = Awaited<
        ReturnType<typeof generatePdfTableControllerGeneratePdfTable>
    >,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<
                        typeof generatePdfTableControllerGeneratePdfTable
                    >
                >,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGeneratePdfTableControllerGeneratePdfTableQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof generatePdfTableControllerGeneratePdfTable>>
    > = ({ signal }) =>
        generatePdfTableControllerGeneratePdfTable(id, {
            signal,
            ...requestOptions,
        });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof generatePdfTableControllerGeneratePdfTable>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GeneratePdfTableControllerGeneratePdfTableQueryResult = NonNullable<
    Awaited<ReturnType<typeof generatePdfTableControllerGeneratePdfTable>>
>;
export type GeneratePdfTableControllerGeneratePdfTableQueryError = void;

export function useGeneratePdfTableControllerGeneratePdfTable<
    TData = Awaited<
        ReturnType<typeof generatePdfTableControllerGeneratePdfTable>
    >,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<
                        typeof generatePdfTableControllerGeneratePdfTable
                    >
                >,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<
                        ReturnType<
                            typeof generatePdfTableControllerGeneratePdfTable
                        >
                    >,
                    TError,
                    Awaited<
                        ReturnType<
                            typeof generatePdfTableControllerGeneratePdfTable
                        >
                    >
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGeneratePdfTableControllerGeneratePdfTable<
    TData = Awaited<
        ReturnType<typeof generatePdfTableControllerGeneratePdfTable>
    >,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<
                        typeof generatePdfTableControllerGeneratePdfTable
                    >
                >,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<
                        ReturnType<
                            typeof generatePdfTableControllerGeneratePdfTable
                        >
                    >,
                    TError,
                    Awaited<
                        ReturnType<
                            typeof generatePdfTableControllerGeneratePdfTable
                        >
                    >
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGeneratePdfTableControllerGeneratePdfTable<
    TData = Awaited<
        ReturnType<typeof generatePdfTableControllerGeneratePdfTable>
    >,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<
                        typeof generatePdfTableControllerGeneratePdfTable
                    >
                >,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить PDF сметы для отображения
 */

export function useGeneratePdfTableControllerGeneratePdfTable<
    TData = Awaited<
        ReturnType<typeof generatePdfTableControllerGeneratePdfTable>
    >,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<
                    ReturnType<
                        typeof generatePdfTableControllerGeneratePdfTable
                    >
                >,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions =
        getGeneratePdfTableControllerGeneratePdfTableQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
