/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AdminCreateDto,
    AdminLoginDto,
    AdminWithoutPasswordDto,
} from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Авторизация администратора
 */
export type adminControllerLoginResponse200 = {
    data: void;
    status: 200;
};

export type adminControllerLoginResponse401 = {
    data: void;
    status: 401;
};

export type adminControllerLoginResponse429 = {
    data: void;
    status: 429;
};

export type adminControllerLoginResponseSuccess =
    adminControllerLoginResponse200 & {
        headers: Headers;
    };
export type adminControllerLoginResponseError = (
    | adminControllerLoginResponse401
    | adminControllerLoginResponse429
) & {
    headers: Headers;
};

export type adminControllerLoginResponse =
    | adminControllerLoginResponseSuccess
    | adminControllerLoginResponseError;

export const getAdminControllerLoginUrl = () => {
    return `/api/admin/login`;
};

export const adminControllerLogin = async (
    adminLoginDto: AdminLoginDto,
    options?: RequestInit,
): Promise<adminControllerLoginResponse> => {
    return customInstance<adminControllerLoginResponse>(
        getAdminControllerLoginUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(adminLoginDto),
        },
    );
};

export const getAdminControllerLoginMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminControllerLogin>>,
        TError,
        { data: AdminLoginDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerLogin>>,
    TError,
    { data: AdminLoginDto },
    TContext
> => {
    const mutationKey = ["adminControllerLogin"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminControllerLogin>>,
        { data: AdminLoginDto }
    > = (props) => {
        const { data } = props ?? {};

        return adminControllerLogin(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminControllerLoginMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerLogin>>
>;
export type AdminControllerLoginMutationBody = AdminLoginDto;
export type AdminControllerLoginMutationError = void;

/**
 * @summary Авторизация администратора
 */
export const useAdminControllerLogin = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminControllerLogin>>,
            TError,
            { data: AdminLoginDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof adminControllerLogin>>,
    TError,
    { data: AdminLoginDto },
    TContext
> => {
    return useMutation(
        getAdminControllerLoginMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Получить всех администраторов
 */
export type adminControllerGetAllResponse200 = {
    data: AdminWithoutPasswordDto[];
    status: 200;
};

export type adminControllerGetAllResponse401 = {
    data: void;
    status: 401;
};

export type adminControllerGetAllResponse403 = {
    data: void;
    status: 403;
};

export type adminControllerGetAllResponseSuccess =
    adminControllerGetAllResponse200 & {
        headers: Headers;
    };
export type adminControllerGetAllResponseError = (
    | adminControllerGetAllResponse401
    | adminControllerGetAllResponse403
) & {
    headers: Headers;
};

export type adminControllerGetAllResponse =
    | adminControllerGetAllResponseSuccess
    | adminControllerGetAllResponseError;

export const getAdminControllerGetAllUrl = () => {
    return `/api/admin`;
};

export const adminControllerGetAll = async (
    options?: RequestInit,
): Promise<adminControllerGetAllResponse> => {
    return customInstance<adminControllerGetAllResponse>(
        getAdminControllerGetAllUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getAdminControllerGetAllQueryKey = () => {
    return [`/api/admin`] as const;
};

export const getAdminControllerGetAllQueryOptions = <
    TData = Awaited<ReturnType<typeof adminControllerGetAll>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminControllerGetAll>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getAdminControllerGetAllQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminControllerGetAll>>
    > = ({ signal }) => adminControllerGetAll({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAll>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerGetAllQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerGetAll>>
>;
export type AdminControllerGetAllQueryError = void;

export function useAdminControllerGetAll<
    TData = Awaited<ReturnType<typeof adminControllerGetAll>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof adminControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetAll<
    TData = Awaited<ReturnType<typeof adminControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof adminControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetAll<
    TData = Awaited<ReturnType<typeof adminControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить всех администраторов
 */

export function useAdminControllerGetAll<
    TData = Awaited<ReturnType<typeof adminControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminControllerGetAllQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Получить текущего администратора
 */
export type adminControllerGetCurrentAdminResponse200 = {
    data: AdminWithoutPasswordDto;
    status: 200;
};

export type adminControllerGetCurrentAdminResponse401 = {
    data: void;
    status: 401;
};

export type adminControllerGetCurrentAdminResponse404 = {
    data: void;
    status: 404;
};

export type adminControllerGetCurrentAdminResponseSuccess =
    adminControllerGetCurrentAdminResponse200 & {
        headers: Headers;
    };
export type adminControllerGetCurrentAdminResponseError = (
    | adminControllerGetCurrentAdminResponse401
    | adminControllerGetCurrentAdminResponse404
) & {
    headers: Headers;
};

export type adminControllerGetCurrentAdminResponse =
    | adminControllerGetCurrentAdminResponseSuccess
    | adminControllerGetCurrentAdminResponseError;

export const getAdminControllerGetCurrentAdminUrl = () => {
    return `/api/admin/me`;
};

export const adminControllerGetCurrentAdmin = async (
    options?: RequestInit,
): Promise<adminControllerGetCurrentAdminResponse> => {
    return customInstance<adminControllerGetCurrentAdminResponse>(
        getAdminControllerGetCurrentAdminUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getAdminControllerGetCurrentAdminQueryKey = () => {
    return [`/api/admin/me`] as const;
};

export const getAdminControllerGetCurrentAdminQueryOptions = <
    TData = Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getAdminControllerGetCurrentAdminQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>
    > = ({ signal }) =>
        adminControllerGetCurrentAdmin({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerGetCurrentAdminQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>
>;
export type AdminControllerGetCurrentAdminQueryError = void;

export function useAdminControllerGetCurrentAdmin<
    TData = Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                    TError,
                    Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetCurrentAdmin<
    TData = Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                    TError,
                    Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetCurrentAdmin<
    TData = Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить текущего администратора
 */

export function useAdminControllerGetCurrentAdmin<
    TData = Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminControllerGetCurrentAdmin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminControllerGetCurrentAdminQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Создать администратора
 */
export type adminControllerCreateResponse201 = {
    data: AdminWithoutPasswordDto;
    status: 201;
};

export type adminControllerCreateResponse400 = {
    data: void;
    status: 400;
};

export type adminControllerCreateResponse403 = {
    data: void;
    status: 403;
};

export type adminControllerCreateResponseSuccess =
    adminControllerCreateResponse201 & {
        headers: Headers;
    };
export type adminControllerCreateResponseError = (
    | adminControllerCreateResponse400
    | adminControllerCreateResponse403
) & {
    headers: Headers;
};

export type adminControllerCreateResponse =
    | adminControllerCreateResponseSuccess
    | adminControllerCreateResponseError;

export const getAdminControllerCreateUrl = () => {
    return `/api/admin/create`;
};

export const adminControllerCreate = async (
    adminCreateDto: AdminCreateDto,
    options?: RequestInit,
): Promise<adminControllerCreateResponse> => {
    return customInstance<adminControllerCreateResponse>(
        getAdminControllerCreateUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(adminCreateDto),
        },
    );
};

export const getAdminControllerCreateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminControllerCreate>>,
        TError,
        { data: AdminCreateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerCreate>>,
    TError,
    { data: AdminCreateDto },
    TContext
> => {
    const mutationKey = ["adminControllerCreate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminControllerCreate>>,
        { data: AdminCreateDto }
    > = (props) => {
        const { data } = props ?? {};

        return adminControllerCreate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminControllerCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerCreate>>
>;
export type AdminControllerCreateMutationBody = AdminCreateDto;
export type AdminControllerCreateMutationError = void;

/**
 * @summary Создать администратора
 */
export const useAdminControllerCreate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminControllerCreate>>,
            TError,
            { data: AdminCreateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof adminControllerCreate>>,
    TError,
    { data: AdminCreateDto },
    TContext
> => {
    return useMutation(
        getAdminControllerCreateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Обновить роль администратора
 */
export type adminControllerUpdateRoleResponse200 = {
    data: void;
    status: 200;
};

export type adminControllerUpdateRoleResponse401 = {
    data: void;
    status: 401;
};

export type adminControllerUpdateRoleResponse403 = {
    data: void;
    status: 403;
};

export type adminControllerUpdateRoleResponse404 = {
    data: void;
    status: 404;
};

export type adminControllerUpdateRoleResponseSuccess =
    adminControllerUpdateRoleResponse200 & {
        headers: Headers;
    };
export type adminControllerUpdateRoleResponseError = (
    | adminControllerUpdateRoleResponse401
    | adminControllerUpdateRoleResponse403
    | adminControllerUpdateRoleResponse404
) & {
    headers: Headers;
};

export type adminControllerUpdateRoleResponse =
    | adminControllerUpdateRoleResponseSuccess
    | adminControllerUpdateRoleResponseError;

export const getAdminControllerUpdateRoleUrl = (id: number) => {
    return `/api/admin/${id}`;
};

export const adminControllerUpdateRole = async (
    id: number,
    options?: RequestInit,
): Promise<adminControllerUpdateRoleResponse> => {
    return customInstance<adminControllerUpdateRoleResponse>(
        getAdminControllerUpdateRoleUrl(id),
        {
            ...options,
            method: "PUT",
        },
    );
};

export const getAdminControllerUpdateRoleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminControllerUpdateRole>>,
        TError,
        { id: number },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerUpdateRole>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["adminControllerUpdateRole"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminControllerUpdateRole>>,
        { id: number }
    > = (props) => {
        const { id } = props ?? {};

        return adminControllerUpdateRole(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminControllerUpdateRoleMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerUpdateRole>>
>;

export type AdminControllerUpdateRoleMutationError = void;

/**
 * @summary Обновить роль администратора
 */
export const useAdminControllerUpdateRole = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminControllerUpdateRole>>,
            TError,
            { id: number },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof adminControllerUpdateRole>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getAdminControllerUpdateRoleMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Удалить администратора
 */
export type adminControllerDeleteResponse200 = {
    data: void;
    status: 200;
};

export type adminControllerDeleteResponse401 = {
    data: void;
    status: 401;
};

export type adminControllerDeleteResponse403 = {
    data: void;
    status: 403;
};

export type adminControllerDeleteResponse404 = {
    data: void;
    status: 404;
};

export type adminControllerDeleteResponseSuccess =
    adminControllerDeleteResponse200 & {
        headers: Headers;
    };
export type adminControllerDeleteResponseError = (
    | adminControllerDeleteResponse401
    | adminControllerDeleteResponse403
    | adminControllerDeleteResponse404
) & {
    headers: Headers;
};

export type adminControllerDeleteResponse =
    | adminControllerDeleteResponseSuccess
    | adminControllerDeleteResponseError;

export const getAdminControllerDeleteUrl = (id: number) => {
    return `/api/admin/${id}`;
};

export const adminControllerDelete = async (
    id: number,
    options?: RequestInit,
): Promise<adminControllerDeleteResponse> => {
    return customInstance<adminControllerDeleteResponse>(
        getAdminControllerDeleteUrl(id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getAdminControllerDeleteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof adminControllerDelete>>,
        TError,
        { id: number },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["adminControllerDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminControllerDelete>>,
        { id: number }
    > = (props) => {
        const { id } = props ?? {};

        return adminControllerDelete(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminControllerDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminControllerDelete>>
>;

export type AdminControllerDeleteMutationError = void;

/**
 * @summary Удалить администратора
 */
export const useAdminControllerDelete = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof adminControllerDelete>>,
            TError,
            { id: number },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof adminControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getAdminControllerDeleteMutationOptions(options),
        queryClient,
    );
};
