/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    NodeDesignCreateDto,
    NodeDesignDto,
    NodeDesignUpdateDto,
} from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить все вариации конструкции узлов продуктов
 */
export type nodeDesignControllerGetAllResponse200 = {
    data: NodeDesignDto[];
    status: 200;
};

export type nodeDesignControllerGetAllResponse401 = {
    data: void;
    status: 401;
};

export type nodeDesignControllerGetAllResponseSuccess =
    nodeDesignControllerGetAllResponse200 & {
        headers: Headers;
    };
export type nodeDesignControllerGetAllResponseError =
    nodeDesignControllerGetAllResponse401 & {
        headers: Headers;
    };

export type nodeDesignControllerGetAllResponse =
    | nodeDesignControllerGetAllResponseSuccess
    | nodeDesignControllerGetAllResponseError;

export const getNodeDesignControllerGetAllUrl = () => {
    return `/api/admin/node-design`;
};

export const nodeDesignControllerGetAll = async (
    options?: RequestInit,
): Promise<nodeDesignControllerGetAllResponse> => {
    return customInstance<nodeDesignControllerGetAllResponse>(
        getNodeDesignControllerGetAllUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getNodeDesignControllerGetAllQueryKey = () => {
    return [`/api/admin/node-design`] as const;
};

export const getNodeDesignControllerGetAllQueryOptions = <
    TData = Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getNodeDesignControllerGetAllQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof nodeDesignControllerGetAll>>
    > = ({ signal }) =>
        nodeDesignControllerGetAll({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NodeDesignControllerGetAllQueryResult = NonNullable<
    Awaited<ReturnType<typeof nodeDesignControllerGetAll>>
>;
export type NodeDesignControllerGetAllQueryError = void;

export function useNodeDesignControllerGetAll<
    TData = Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof nodeDesignControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNodeDesignControllerGetAll<
    TData = Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof nodeDesignControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNodeDesignControllerGetAll<
    TData = Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить все вариации конструкции узлов продуктов
 */

export function useNodeDesignControllerGetAll<
    TData = Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getNodeDesignControllerGetAllQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Создать вариацию конструкции узлов продуктов
 */
export type nodeDesignControllerCreateResponse201 = {
    data: NodeDesignDto;
    status: 201;
};

export type nodeDesignControllerCreateResponse400 = {
    data: void;
    status: 400;
};

export type nodeDesignControllerCreateResponse401 = {
    data: void;
    status: 401;
};

export type nodeDesignControllerCreateResponseSuccess =
    nodeDesignControllerCreateResponse201 & {
        headers: Headers;
    };
export type nodeDesignControllerCreateResponseError = (
    | nodeDesignControllerCreateResponse400
    | nodeDesignControllerCreateResponse401
) & {
    headers: Headers;
};

export type nodeDesignControllerCreateResponse =
    | nodeDesignControllerCreateResponseSuccess
    | nodeDesignControllerCreateResponseError;

export const getNodeDesignControllerCreateUrl = () => {
    return `/api/admin/node-design`;
};

export const nodeDesignControllerCreate = async (
    nodeDesignCreateDto: NodeDesignCreateDto,
    options?: RequestInit,
): Promise<nodeDesignControllerCreateResponse> => {
    return customInstance<nodeDesignControllerCreateResponse>(
        getNodeDesignControllerCreateUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(nodeDesignCreateDto),
        },
    );
};

export const getNodeDesignControllerCreateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof nodeDesignControllerCreate>>,
        TError,
        { data: NodeDesignCreateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof nodeDesignControllerCreate>>,
    TError,
    { data: NodeDesignCreateDto },
    TContext
> => {
    const mutationKey = ["nodeDesignControllerCreate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof nodeDesignControllerCreate>>,
        { data: NodeDesignCreateDto }
    > = (props) => {
        const { data } = props ?? {};

        return nodeDesignControllerCreate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type NodeDesignControllerCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof nodeDesignControllerCreate>>
>;
export type NodeDesignControllerCreateMutationBody = NodeDesignCreateDto;
export type NodeDesignControllerCreateMutationError = void;

/**
 * @summary Создать вариацию конструкции узлов продуктов
 */
export const useNodeDesignControllerCreate = <
    TError = void,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof nodeDesignControllerCreate>>,
            TError,
            { data: NodeDesignCreateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof nodeDesignControllerCreate>>,
    TError,
    { data: NodeDesignCreateDto },
    TContext
> => {
    return useMutation(
        getNodeDesignControllerCreateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Получить вариацию конструкции узлов продуктов по ID
 */
export type nodeDesignControllerFindByIdResponse200 = {
    data: NodeDesignDto;
    status: 200;
};

export type nodeDesignControllerFindByIdResponse401 = {
    data: void;
    status: 401;
};

export type nodeDesignControllerFindByIdResponse404 = {
    data: void;
    status: 404;
};

export type nodeDesignControllerFindByIdResponseSuccess =
    nodeDesignControllerFindByIdResponse200 & {
        headers: Headers;
    };
export type nodeDesignControllerFindByIdResponseError = (
    | nodeDesignControllerFindByIdResponse401
    | nodeDesignControllerFindByIdResponse404
) & {
    headers: Headers;
};

export type nodeDesignControllerFindByIdResponse =
    | nodeDesignControllerFindByIdResponseSuccess
    | nodeDesignControllerFindByIdResponseError;

export const getNodeDesignControllerFindByIdUrl = (id: number) => {
    return `/api/admin/node-design/${id}`;
};

export const nodeDesignControllerFindById = async (
    id: number,
    options?: RequestInit,
): Promise<nodeDesignControllerFindByIdResponse> => {
    return customInstance<nodeDesignControllerFindByIdResponse>(
        getNodeDesignControllerFindByIdUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getNodeDesignControllerFindByIdQueryKey = (id: number) => {
    return [`/api/admin/node-design/${id}`] as const;
};

export const getNodeDesignControllerFindByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getNodeDesignControllerFindByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof nodeDesignControllerFindById>>
    > = ({ signal }) =>
        nodeDesignControllerFindById(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NodeDesignControllerFindByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof nodeDesignControllerFindById>>
>;
export type NodeDesignControllerFindByIdQueryError = void;

export function useNodeDesignControllerFindById<
    TData = Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
    TError = void,
>(
    id: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof nodeDesignControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNodeDesignControllerFindById<
    TData = Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof nodeDesignControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNodeDesignControllerFindById<
    TData = Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить вариацию конструкции узлов продуктов по ID
 */

export function useNodeDesignControllerFindById<
    TData = Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof nodeDesignControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getNodeDesignControllerFindByIdQueryOptions(
        id,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить вариацию конструкции узлов продуктов
 */
export type nodeDesignControllerUpdateResponse200 = {
    data: NodeDesignDto;
    status: 200;
};

export type nodeDesignControllerUpdateResponse400 = {
    data: void;
    status: 400;
};

export type nodeDesignControllerUpdateResponse401 = {
    data: void;
    status: 401;
};

export type nodeDesignControllerUpdateResponseSuccess =
    nodeDesignControllerUpdateResponse200 & {
        headers: Headers;
    };
export type nodeDesignControllerUpdateResponseError = (
    | nodeDesignControllerUpdateResponse400
    | nodeDesignControllerUpdateResponse401
) & {
    headers: Headers;
};

export type nodeDesignControllerUpdateResponse =
    | nodeDesignControllerUpdateResponseSuccess
    | nodeDesignControllerUpdateResponseError;

export const getNodeDesignControllerUpdateUrl = (id: number) => {
    return `/api/admin/node-design/${id}`;
};

export const nodeDesignControllerUpdate = async (
    id: number,
    nodeDesignUpdateDto: NodeDesignUpdateDto,
    options?: RequestInit,
): Promise<nodeDesignControllerUpdateResponse> => {
    return customInstance<nodeDesignControllerUpdateResponse>(
        getNodeDesignControllerUpdateUrl(id),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(nodeDesignUpdateDto),
        },
    );
};

export const getNodeDesignControllerUpdateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof nodeDesignControllerUpdate>>,
        TError,
        { id: number; data: NodeDesignUpdateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof nodeDesignControllerUpdate>>,
    TError,
    { id: number; data: NodeDesignUpdateDto },
    TContext
> => {
    const mutationKey = ["nodeDesignControllerUpdate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof nodeDesignControllerUpdate>>,
        { id: number; data: NodeDesignUpdateDto }
    > = (props) => {
        const { id, data } = props ?? {};

        return nodeDesignControllerUpdate(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type NodeDesignControllerUpdateMutationResult = NonNullable<
    Awaited<ReturnType<typeof nodeDesignControllerUpdate>>
>;
export type NodeDesignControllerUpdateMutationBody = NodeDesignUpdateDto;
export type NodeDesignControllerUpdateMutationError = void;

/**
 * @summary Обновить вариацию конструкции узлов продуктов
 */
export const useNodeDesignControllerUpdate = <
    TError = void,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof nodeDesignControllerUpdate>>,
            TError,
            { id: number; data: NodeDesignUpdateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof nodeDesignControllerUpdate>>,
    TError,
    { id: number; data: NodeDesignUpdateDto },
    TContext
> => {
    return useMutation(
        getNodeDesignControllerUpdateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Удалить вариацию конструкции узлов продуктов
 */
export type nodeDesignControllerDeleteResponse200 = {
    data: NodeDesignDto;
    status: 200;
};

export type nodeDesignControllerDeleteResponse401 = {
    data: void;
    status: 401;
};

export type nodeDesignControllerDeleteResponse404 = {
    data: void;
    status: 404;
};

export type nodeDesignControllerDeleteResponseSuccess =
    nodeDesignControllerDeleteResponse200 & {
        headers: Headers;
    };
export type nodeDesignControllerDeleteResponseError = (
    | nodeDesignControllerDeleteResponse401
    | nodeDesignControllerDeleteResponse404
) & {
    headers: Headers;
};

export type nodeDesignControllerDeleteResponse =
    | nodeDesignControllerDeleteResponseSuccess
    | nodeDesignControllerDeleteResponseError;

export const getNodeDesignControllerDeleteUrl = (id: number) => {
    return `/api/admin/node-design/${id}`;
};

export const nodeDesignControllerDelete = async (
    id: number,
    options?: RequestInit,
): Promise<nodeDesignControllerDeleteResponse> => {
    return customInstance<nodeDesignControllerDeleteResponse>(
        getNodeDesignControllerDeleteUrl(id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getNodeDesignControllerDeleteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof nodeDesignControllerDelete>>,
        TError,
        { id: number },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof nodeDesignControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["nodeDesignControllerDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof nodeDesignControllerDelete>>,
        { id: number }
    > = (props) => {
        const { id } = props ?? {};

        return nodeDesignControllerDelete(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type NodeDesignControllerDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof nodeDesignControllerDelete>>
>;

export type NodeDesignControllerDeleteMutationError = void;

/**
 * @summary Удалить вариацию конструкции узлов продуктов
 */
export const useNodeDesignControllerDelete = <
    TError = void,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof nodeDesignControllerDelete>>,
            TError,
            { id: number },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof nodeDesignControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getNodeDesignControllerDeleteMutationOptions(options),
        queryClient,
    );
};
