/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type { KpDto } from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить КП по ID
 */
export type getKpControllerGetKpResponse200 = {
    data: KpDto;
    status: 200;
};

export type getKpControllerGetKpResponse404 = {
    data: void;
    status: 404;
};

export type getKpControllerGetKpResponseSuccess =
    getKpControllerGetKpResponse200 & {
        headers: Headers;
    };
export type getKpControllerGetKpResponseError =
    getKpControllerGetKpResponse404 & {
        headers: Headers;
    };

export type getKpControllerGetKpResponse =
    | getKpControllerGetKpResponseSuccess
    | getKpControllerGetKpResponseError;

export const getGetKpControllerGetKpUrl = (id: string) => {
    return `/api/get-kp/${id}`;
};

export const getKpControllerGetKp = async (
    id: string,
    options?: RequestInit,
): Promise<getKpControllerGetKpResponse> => {
    return customInstance<getKpControllerGetKpResponse>(
        getGetKpControllerGetKpUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetKpControllerGetKpQueryKey = (id: string) => {
    return [`/api/get-kp/${id}`] as const;
};

export const getGetKpControllerGetKpQueryOptions = <
    TData = Awaited<ReturnType<typeof getKpControllerGetKp>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getKpControllerGetKp>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetKpControllerGetKpQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getKpControllerGetKp>>
    > = ({ signal }) => getKpControllerGetKp(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getKpControllerGetKp>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetKpControllerGetKpQueryResult = NonNullable<
    Awaited<ReturnType<typeof getKpControllerGetKp>>
>;
export type GetKpControllerGetKpQueryError = void;

export function useGetKpControllerGetKp<
    TData = Awaited<ReturnType<typeof getKpControllerGetKp>>,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getKpControllerGetKp>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getKpControllerGetKp>>,
                    TError,
                    Awaited<ReturnType<typeof getKpControllerGetKp>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKpControllerGetKp<
    TData = Awaited<ReturnType<typeof getKpControllerGetKp>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getKpControllerGetKp>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getKpControllerGetKp>>,
                    TError,
                    Awaited<ReturnType<typeof getKpControllerGetKp>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKpControllerGetKp<
    TData = Awaited<ReturnType<typeof getKpControllerGetKp>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getKpControllerGetKp>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить КП по ID
 */

export function useGetKpControllerGetKp<
    TData = Awaited<ReturnType<typeof getKpControllerGetKp>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getKpControllerGetKp>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetKpControllerGetKpQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
