/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    ManagerCreateDto,
    ManagerDto,
    ManagerUpdateDto,
} from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить всех менеджеров
 */
export type managerControllerGetAllResponse200 = {
    data: ManagerDto[];
    status: 200;
};

export type managerControllerGetAllResponse401 = {
    data: void;
    status: 401;
};

export type managerControllerGetAllResponseSuccess =
    managerControllerGetAllResponse200 & {
        headers: Headers;
    };
export type managerControllerGetAllResponseError =
    managerControllerGetAllResponse401 & {
        headers: Headers;
    };

export type managerControllerGetAllResponse =
    | managerControllerGetAllResponseSuccess
    | managerControllerGetAllResponseError;

export const getManagerControllerGetAllUrl = () => {
    return `/api/admin/manager`;
};

export const managerControllerGetAll = async (
    options?: RequestInit,
): Promise<managerControllerGetAllResponse> => {
    return customInstance<managerControllerGetAllResponse>(
        getManagerControllerGetAllUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getManagerControllerGetAllQueryKey = () => {
    return [`/api/admin/manager`] as const;
};

export const getManagerControllerGetAllQueryOptions = <
    TData = Awaited<ReturnType<typeof managerControllerGetAll>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof managerControllerGetAll>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getManagerControllerGetAllQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof managerControllerGetAll>>
    > = ({ signal }) => managerControllerGetAll({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof managerControllerGetAll>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ManagerControllerGetAllQueryResult = NonNullable<
    Awaited<ReturnType<typeof managerControllerGetAll>>
>;
export type ManagerControllerGetAllQueryError = void;

export function useManagerControllerGetAll<
    TData = Awaited<ReturnType<typeof managerControllerGetAll>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof managerControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof managerControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useManagerControllerGetAll<
    TData = Awaited<ReturnType<typeof managerControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof managerControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof managerControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useManagerControllerGetAll<
    TData = Awaited<ReturnType<typeof managerControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить всех менеджеров
 */

export function useManagerControllerGetAll<
    TData = Awaited<ReturnType<typeof managerControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getManagerControllerGetAllQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Создать менеджера
 */
export type managerControllerCreateResponse201 = {
    data: ManagerDto;
    status: 201;
};

export type managerControllerCreateResponse400 = {
    data: void;
    status: 400;
};

export type managerControllerCreateResponse401 = {
    data: void;
    status: 401;
};

export type managerControllerCreateResponseSuccess =
    managerControllerCreateResponse201 & {
        headers: Headers;
    };
export type managerControllerCreateResponseError = (
    | managerControllerCreateResponse400
    | managerControllerCreateResponse401
) & {
    headers: Headers;
};

export type managerControllerCreateResponse =
    | managerControllerCreateResponseSuccess
    | managerControllerCreateResponseError;

export const getManagerControllerCreateUrl = () => {
    return `/api/admin/manager`;
};

export const managerControllerCreate = async (
    managerCreateDto: ManagerCreateDto,
    options?: RequestInit,
): Promise<managerControllerCreateResponse> => {
    return customInstance<managerControllerCreateResponse>(
        getManagerControllerCreateUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(managerCreateDto),
        },
    );
};

export const getManagerControllerCreateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof managerControllerCreate>>,
        TError,
        { data: ManagerCreateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof managerControllerCreate>>,
    TError,
    { data: ManagerCreateDto },
    TContext
> => {
    const mutationKey = ["managerControllerCreate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof managerControllerCreate>>,
        { data: ManagerCreateDto }
    > = (props) => {
        const { data } = props ?? {};

        return managerControllerCreate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ManagerControllerCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof managerControllerCreate>>
>;
export type ManagerControllerCreateMutationBody = ManagerCreateDto;
export type ManagerControllerCreateMutationError = void;

/**
 * @summary Создать менеджера
 */
export const useManagerControllerCreate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof managerControllerCreate>>,
            TError,
            { data: ManagerCreateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof managerControllerCreate>>,
    TError,
    { data: ManagerCreateDto },
    TContext
> => {
    return useMutation(
        getManagerControllerCreateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Получить менеджера по ID
 */
export type managerControllerFindByIdResponse200 = {
    data: ManagerDto;
    status: 200;
};

export type managerControllerFindByIdResponse401 = {
    data: void;
    status: 401;
};

export type managerControllerFindByIdResponse404 = {
    data: void;
    status: 404;
};

export type managerControllerFindByIdResponseSuccess =
    managerControllerFindByIdResponse200 & {
        headers: Headers;
    };
export type managerControllerFindByIdResponseError = (
    | managerControllerFindByIdResponse401
    | managerControllerFindByIdResponse404
) & {
    headers: Headers;
};

export type managerControllerFindByIdResponse =
    | managerControllerFindByIdResponseSuccess
    | managerControllerFindByIdResponseError;

export const getManagerControllerFindByIdUrl = (id: number) => {
    return `/api/admin/manager/${id}`;
};

export const managerControllerFindById = async (
    id: number,
    options?: RequestInit,
): Promise<managerControllerFindByIdResponse> => {
    return customInstance<managerControllerFindByIdResponse>(
        getManagerControllerFindByIdUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getManagerControllerFindByIdQueryKey = (id: number) => {
    return [`/api/admin/manager/${id}`] as const;
};

export const getManagerControllerFindByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof managerControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getManagerControllerFindByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof managerControllerFindById>>
    > = ({ signal }) =>
        managerControllerFindById(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof managerControllerFindById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ManagerControllerFindByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof managerControllerFindById>>
>;
export type ManagerControllerFindByIdQueryError = void;

export function useManagerControllerFindById<
    TData = Awaited<ReturnType<typeof managerControllerFindById>>,
    TError = void,
>(
    id: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof managerControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof managerControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useManagerControllerFindById<
    TData = Awaited<ReturnType<typeof managerControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof managerControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof managerControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useManagerControllerFindById<
    TData = Awaited<ReturnType<typeof managerControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить менеджера по ID
 */

export function useManagerControllerFindById<
    TData = Awaited<ReturnType<typeof managerControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof managerControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getManagerControllerFindByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить менеджера
 */
export type managerControllerUpdateResponse200 = {
    data: ManagerDto;
    status: 200;
};

export type managerControllerUpdateResponse400 = {
    data: void;
    status: 400;
};

export type managerControllerUpdateResponse401 = {
    data: void;
    status: 401;
};

export type managerControllerUpdateResponseSuccess =
    managerControllerUpdateResponse200 & {
        headers: Headers;
    };
export type managerControllerUpdateResponseError = (
    | managerControllerUpdateResponse400
    | managerControllerUpdateResponse401
) & {
    headers: Headers;
};

export type managerControllerUpdateResponse =
    | managerControllerUpdateResponseSuccess
    | managerControllerUpdateResponseError;

export const getManagerControllerUpdateUrl = (id: number) => {
    return `/api/admin/manager/${id}`;
};

export const managerControllerUpdate = async (
    id: number,
    managerUpdateDto: ManagerUpdateDto,
    options?: RequestInit,
): Promise<managerControllerUpdateResponse> => {
    return customInstance<managerControllerUpdateResponse>(
        getManagerControllerUpdateUrl(id),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(managerUpdateDto),
        },
    );
};

export const getManagerControllerUpdateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof managerControllerUpdate>>,
        TError,
        { id: number; data: ManagerUpdateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof managerControllerUpdate>>,
    TError,
    { id: number; data: ManagerUpdateDto },
    TContext
> => {
    const mutationKey = ["managerControllerUpdate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof managerControllerUpdate>>,
        { id: number; data: ManagerUpdateDto }
    > = (props) => {
        const { id, data } = props ?? {};

        return managerControllerUpdate(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ManagerControllerUpdateMutationResult = NonNullable<
    Awaited<ReturnType<typeof managerControllerUpdate>>
>;
export type ManagerControllerUpdateMutationBody = ManagerUpdateDto;
export type ManagerControllerUpdateMutationError = void;

/**
 * @summary Обновить менеджера
 */
export const useManagerControllerUpdate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof managerControllerUpdate>>,
            TError,
            { id: number; data: ManagerUpdateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof managerControllerUpdate>>,
    TError,
    { id: number; data: ManagerUpdateDto },
    TContext
> => {
    return useMutation(
        getManagerControllerUpdateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Удалить менеджера
 */
export type managerControllerDeleteResponse200 = {
    data: ManagerDto;
    status: 200;
};

export type managerControllerDeleteResponse401 = {
    data: void;
    status: 401;
};

export type managerControllerDeleteResponse404 = {
    data: void;
    status: 404;
};

export type managerControllerDeleteResponseSuccess =
    managerControllerDeleteResponse200 & {
        headers: Headers;
    };
export type managerControllerDeleteResponseError = (
    | managerControllerDeleteResponse401
    | managerControllerDeleteResponse404
) & {
    headers: Headers;
};

export type managerControllerDeleteResponse =
    | managerControllerDeleteResponseSuccess
    | managerControllerDeleteResponseError;

export const getManagerControllerDeleteUrl = (id: number) => {
    return `/api/admin/manager/${id}`;
};

export const managerControllerDelete = async (
    id: number,
    options?: RequestInit,
): Promise<managerControllerDeleteResponse> => {
    return customInstance<managerControllerDeleteResponse>(
        getManagerControllerDeleteUrl(id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getManagerControllerDeleteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof managerControllerDelete>>,
        TError,
        { id: number },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof managerControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["managerControllerDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof managerControllerDelete>>,
        { id: number }
    > = (props) => {
        const { id } = props ?? {};

        return managerControllerDelete(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ManagerControllerDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof managerControllerDelete>>
>;

export type ManagerControllerDeleteMutationError = void;

/**
 * @summary Удалить менеджера
 */
export const useManagerControllerDelete = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof managerControllerDelete>>,
            TError,
            { id: number },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof managerControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getManagerControllerDeleteMutationOptions(options),
        queryClient,
    );
};
