/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type { GetDocumentControllerGetDocumentParams } from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить файл по пути (в пределах uploads)
 */
export type getDocumentControllerGetDocumentResponse200 = {
    data: void;
    status: 200;
};

export type getDocumentControllerGetDocumentResponse404 = {
    data: void;
    status: 404;
};

export type getDocumentControllerGetDocumentResponseSuccess =
    getDocumentControllerGetDocumentResponse200 & {
        headers: Headers;
    };
export type getDocumentControllerGetDocumentResponseError =
    getDocumentControllerGetDocumentResponse404 & {
        headers: Headers;
    };

export type getDocumentControllerGetDocumentResponse =
    | getDocumentControllerGetDocumentResponseSuccess
    | getDocumentControllerGetDocumentResponseError;

export const getGetDocumentControllerGetDocumentUrl = (
    params: GetDocumentControllerGetDocumentParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString(),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/get-document?${stringifiedParams}`
        : `/api/get-document`;
};

export const getDocumentControllerGetDocument = async (
    params: GetDocumentControllerGetDocumentParams,
    options?: RequestInit,
): Promise<getDocumentControllerGetDocumentResponse> => {
    return customInstance<getDocumentControllerGetDocumentResponse>(
        getGetDocumentControllerGetDocumentUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetDocumentControllerGetDocumentQueryKey = (
    params?: GetDocumentControllerGetDocumentParams,
) => {
    return [`/api/get-document`, ...(params ? [params] : [])] as const;
};

export const getGetDocumentControllerGetDocumentQueryOptions = <
    TData = Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
    TError = void,
>(
    params: GetDocumentControllerGetDocumentParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGetDocumentControllerGetDocumentQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getDocumentControllerGetDocument>>
    > = ({ signal }) =>
        getDocumentControllerGetDocument(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocumentControllerGetDocumentQueryResult = NonNullable<
    Awaited<ReturnType<typeof getDocumentControllerGetDocument>>
>;
export type GetDocumentControllerGetDocumentQueryError = void;

export function useGetDocumentControllerGetDocument<
    TData = Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
    TError = void,
>(
    params: GetDocumentControllerGetDocumentParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentControllerGetDocument>
                    >,
                    TError,
                    Awaited<ReturnType<typeof getDocumentControllerGetDocument>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocumentControllerGetDocument<
    TData = Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
    TError = void,
>(
    params: GetDocumentControllerGetDocumentParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getDocumentControllerGetDocument>
                    >,
                    TError,
                    Awaited<ReturnType<typeof getDocumentControllerGetDocument>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocumentControllerGetDocument<
    TData = Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
    TError = void,
>(
    params: GetDocumentControllerGetDocumentParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить файл по пути (в пределах uploads)
 */

export function useGetDocumentControllerGetDocument<
    TData = Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
    TError = void,
>(
    params: GetDocumentControllerGetDocumentParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getDocumentControllerGetDocument>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetDocumentControllerGetDocumentQueryOptions(
        params,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
