/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type { CalculationTableDataDto } from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить данных таблицы сметы
 */
export type getTableDataControllerGetTableDataResponse200 = {
    data: CalculationTableDataDto;
    status: 200;
};

export type getTableDataControllerGetTableDataResponse404 = {
    data: void;
    status: 404;
};

export type getTableDataControllerGetTableDataResponse500 = {
    data: void;
    status: 500;
};

export type getTableDataControllerGetTableDataResponseSuccess =
    getTableDataControllerGetTableDataResponse200 & {
        headers: Headers;
    };
export type getTableDataControllerGetTableDataResponseError = (
    | getTableDataControllerGetTableDataResponse404
    | getTableDataControllerGetTableDataResponse500
) & {
    headers: Headers;
};

export type getTableDataControllerGetTableDataResponse =
    | getTableDataControllerGetTableDataResponseSuccess
    | getTableDataControllerGetTableDataResponseError;

export const getGetTableDataControllerGetTableDataUrl = (id: string) => {
    return `/api/get-table-data/${id}`;
};

export const getTableDataControllerGetTableData = async (
    id: string,
    options?: RequestInit,
): Promise<getTableDataControllerGetTableDataResponse> => {
    return customInstance<getTableDataControllerGetTableDataResponse>(
        getGetTableDataControllerGetTableDataUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetTableDataControllerGetTableDataQueryKey = (id: string) => {
    return [`/api/get-table-data/${id}`] as const;
};

export const getGetTableDataControllerGetTableDataQueryOptions = <
    TData = Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGetTableDataControllerGetTableDataQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getTableDataControllerGetTableData>>
    > = ({ signal }) =>
        getTableDataControllerGetTableData(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTableDataControllerGetTableDataQueryResult = NonNullable<
    Awaited<ReturnType<typeof getTableDataControllerGetTableData>>
>;
export type GetTableDataControllerGetTableDataQueryError = void;

export function useGetTableDataControllerGetTableData<
    TData = Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getTableDataControllerGetTableData>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getTableDataControllerGetTableData>
                    >
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTableDataControllerGetTableData<
    TData = Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<
                        ReturnType<typeof getTableDataControllerGetTableData>
                    >,
                    TError,
                    Awaited<
                        ReturnType<typeof getTableDataControllerGetTableData>
                    >
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTableDataControllerGetTableData<
    TData = Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить данных таблицы сметы
 */

export function useGetTableDataControllerGetTableData<
    TData = Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getTableDataControllerGetTableData>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetTableDataControllerGetTableDataQueryOptions(
        id,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
