/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */

/**
 * Роль администратора
 */
export type AdminWithoutPasswordDtoRole =
    (typeof AdminWithoutPasswordDtoRole)[keyof typeof AdminWithoutPasswordDtoRole];

export const AdminWithoutPasswordDtoRole = {
    ADMIN: "ADMIN",
    MODERATOR: "MODERATOR",
} as const;
