/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import type { AdminCreateDtoRole } from "./adminCreateDtoRole";

export interface AdminCreateDto {
    /** Email администратора */
    email: string;
    /** Имя администратора */
    name: string;
    /** Пароль администратора */
    password: string;
    /** Роль администратора */
    role: AdminCreateDtoRole;
}
