/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import type { AdminWithoutPasswordDtoRole } from "./adminWithoutPasswordDtoRole";

export interface AdminWithoutPasswordDto {
    /** ID администратора */
    id: number;
    /** Email администратора */
    email: string;
    /** Имя администратора */
    name: string;
    /** Роль администратора */
    role: AdminWithoutPasswordDtoRole;
}
