/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import type { CalculationTableSectionDto } from "./calculationTableSectionDto";
import type { TotalForFirstSectionDto } from "./totalForFirstSectionDto";

export interface CalculationTableDataDto {
    /** Секции расчётной таблицы */
    sections: CalculationTableSectionDto[];
    /** Итоги по первой секции */
    totalForFirstSection: TotalForFirstSectionDto;
    /** Номер ТР/НР */
    trNr: string;
    /** НДС (%) */
    nds: string;
}
