/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */

export interface CalculationTableRowDto {
    /** Идентификатор строки */
    id: string;
    /** Наименование работы/материала */
    name: string;
    /** Единица измерения */
    unit: string;
    /** Количество */
    quantity: string;
    /** Цена материалов */
    priceMaterials: string;
    /** Стоимость работ */
    costOfWork: string;
    /** Общая стоимость материалов */
    totalCostMaterials: string;
    /** Общая стоимость работ */
    totalCostWork: string;
    /** Общая стоимость */
    totalCost: string;
}
