/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import type { CalculationTableRowDto } from "./calculationTableRowDto";

export interface CalculationTableSectionDto {
    /** Название секции */
    name: string;
    /** Итого по секции */
    total: string;
    /** Строки расчётной таблицы */
    rows: CalculationTableRowDto[];
}
