/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import type { KpDto } from "./kpDto";

export interface ClientDto {
    /** ID клиента */
    id: number;
    /** Имя папки клиента */
    name: string;
    /** Список КП клиента */
    kps?: KpDto[];
}
