/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */

export * from "./adminCreateDto";
export * from "./adminCreateDtoRole";
export * from "./adminLoginDto";
export * from "./adminWithoutPasswordDto";
export * from "./adminWithoutPasswordDtoRole";
export * from "./calculationTableDataDto";
export * from "./calculationTableRowDto";
export * from "./calculationTableSectionDto";
export * from "./clientDto";
export * from "./createClientDto";
export * from "./fileJson";
export * from "./getDocumentControllerGetDocumentParams";
export * from "./kpControllerUploadDocumentsBody";
export * from "./kpControllerUploadEstimateBody";
export * from "./kpCreateDto";
export * from "./kpDto";
export * from "./kpUpdateDto";
export * from "./managerCreateDto";
export * from "./managerDto";
export * from "./managerUpdateDto";
export * from "./nodeDesignCreateDto";
export * from "./nodeDesignDto";
export * from "./nodeDesignUpdateDto";
export * from "./totalForFirstSectionDto";
export * from "./updateClientDto";
