/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */

export interface NodeDesignUpdateDto {
    /** Название вариации конструкции узлов продуктов */
    name: string;
    /** Фото вариации конструкции узлов продуктов */
    photo: string;
}
