/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */

export interface TotalForFirstSectionDto {
    /** Общая стоимость работ по первой секции */
    totalCostWork: string;
    /** Общая стоимость по первой секции */
    totalCost: string;
}
