/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    FileJson,
    KpControllerUploadDocumentsBody,
    KpControllerUploadEstimateBody,
    KpCreateDto,
    KpDto,
    KpUpdateDto,
} from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить все КП
 */
export type kpControllerGetAllResponse200 = {
    data: KpDto[];
    status: 200;
};

export type kpControllerGetAllResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerGetAllResponseSuccess =
    kpControllerGetAllResponse200 & {
        headers: Headers;
    };
export type kpControllerGetAllResponseError = kpControllerGetAllResponse401 & {
    headers: Headers;
};

export type kpControllerGetAllResponse =
    | kpControllerGetAllResponseSuccess
    | kpControllerGetAllResponseError;

export const getKpControllerGetAllUrl = () => {
    return `/api/admin/kp`;
};

export const kpControllerGetAll = async (
    options?: RequestInit,
): Promise<kpControllerGetAllResponse> => {
    return customInstance<kpControllerGetAllResponse>(
        getKpControllerGetAllUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getKpControllerGetAllQueryKey = () => {
    return [`/api/admin/kp`] as const;
};

export const getKpControllerGetAllQueryOptions = <
    TData = Awaited<ReturnType<typeof kpControllerGetAll>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof kpControllerGetAll>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getKpControllerGetAllQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof kpControllerGetAll>>
    > = ({ signal }) => kpControllerGetAll({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof kpControllerGetAll>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type KpControllerGetAllQueryResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerGetAll>>
>;
export type KpControllerGetAllQueryError = void;

export function useKpControllerGetAll<
    TData = Awaited<ReturnType<typeof kpControllerGetAll>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof kpControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof kpControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useKpControllerGetAll<
    TData = Awaited<ReturnType<typeof kpControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof kpControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof kpControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useKpControllerGetAll<
    TData = Awaited<ReturnType<typeof kpControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить все КП
 */

export function useKpControllerGetAll<
    TData = Awaited<ReturnType<typeof kpControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getKpControllerGetAllQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Создать КП
 */
export type kpControllerCreateResponse201 = {
    data: KpDto;
    status: 201;
};

export type kpControllerCreateResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerCreateResponse422 = {
    data: void;
    status: 422;
};

export type kpControllerCreateResponseSuccess =
    kpControllerCreateResponse201 & {
        headers: Headers;
    };
export type kpControllerCreateResponseError = (
    | kpControllerCreateResponse401
    | kpControllerCreateResponse422
) & {
    headers: Headers;
};

export type kpControllerCreateResponse =
    | kpControllerCreateResponseSuccess
    | kpControllerCreateResponseError;

export const getKpControllerCreateUrl = () => {
    return `/api/admin/kp`;
};

export const kpControllerCreate = async (
    kpCreateDto: KpCreateDto,
    options?: RequestInit,
): Promise<kpControllerCreateResponse> => {
    return customInstance<kpControllerCreateResponse>(
        getKpControllerCreateUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(kpCreateDto),
        },
    );
};

export const getKpControllerCreateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof kpControllerCreate>>,
        TError,
        { data: KpCreateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof kpControllerCreate>>,
    TError,
    { data: KpCreateDto },
    TContext
> => {
    const mutationKey = ["kpControllerCreate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof kpControllerCreate>>,
        { data: KpCreateDto }
    > = (props) => {
        const { data } = props ?? {};

        return kpControllerCreate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type KpControllerCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerCreate>>
>;
export type KpControllerCreateMutationBody = KpCreateDto;
export type KpControllerCreateMutationError = void;

/**
 * @summary Создать КП
 */
export const useKpControllerCreate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof kpControllerCreate>>,
            TError,
            { data: KpCreateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof kpControllerCreate>>,
    TError,
    { data: KpCreateDto },
    TContext
> => {
    return useMutation(
        getKpControllerCreateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Получить КП по ID
 */
export type kpControllerFindByIdResponse200 = {
    data: KpDto;
    status: 200;
};

export type kpControllerFindByIdResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerFindByIdResponse404 = {
    data: void;
    status: 404;
};

export type kpControllerFindByIdResponseSuccess =
    kpControllerFindByIdResponse200 & {
        headers: Headers;
    };
export type kpControllerFindByIdResponseError = (
    | kpControllerFindByIdResponse401
    | kpControllerFindByIdResponse404
) & {
    headers: Headers;
};

export type kpControllerFindByIdResponse =
    | kpControllerFindByIdResponseSuccess
    | kpControllerFindByIdResponseError;

export const getKpControllerFindByIdUrl = (id: string) => {
    return `/api/admin/kp/${id}`;
};

export const kpControllerFindById = async (
    id: string,
    options?: RequestInit,
): Promise<kpControllerFindByIdResponse> => {
    return customInstance<kpControllerFindByIdResponse>(
        getKpControllerFindByIdUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getKpControllerFindByIdQueryKey = (id: string) => {
    return [`/api/admin/kp/${id}`] as const;
};

export const getKpControllerFindByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof kpControllerFindById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getKpControllerFindByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof kpControllerFindById>>
    > = ({ signal }) => kpControllerFindById(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof kpControllerFindById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type KpControllerFindByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerFindById>>
>;
export type KpControllerFindByIdQueryError = void;

export function useKpControllerFindById<
    TData = Awaited<ReturnType<typeof kpControllerFindById>>,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof kpControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof kpControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useKpControllerFindById<
    TData = Awaited<ReturnType<typeof kpControllerFindById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof kpControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof kpControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useKpControllerFindById<
    TData = Awaited<ReturnType<typeof kpControllerFindById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить КП по ID
 */

export function useKpControllerFindById<
    TData = Awaited<ReturnType<typeof kpControllerFindById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof kpControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getKpControllerFindByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить КП
 */
export type kpControllerUpdateResponse200 = {
    data: KpDto;
    status: 200;
};

export type kpControllerUpdateResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerUpdateResponse422 = {
    data: void;
    status: 422;
};

export type kpControllerUpdateResponseSuccess =
    kpControllerUpdateResponse200 & {
        headers: Headers;
    };
export type kpControllerUpdateResponseError = (
    | kpControllerUpdateResponse401
    | kpControllerUpdateResponse422
) & {
    headers: Headers;
};

export type kpControllerUpdateResponse =
    | kpControllerUpdateResponseSuccess
    | kpControllerUpdateResponseError;

export const getKpControllerUpdateUrl = (id: string) => {
    return `/api/admin/kp/${id}`;
};

export const kpControllerUpdate = async (
    id: string,
    kpUpdateDto: KpUpdateDto,
    options?: RequestInit,
): Promise<kpControllerUpdateResponse> => {
    return customInstance<kpControllerUpdateResponse>(
        getKpControllerUpdateUrl(id),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(kpUpdateDto),
        },
    );
};

export const getKpControllerUpdateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof kpControllerUpdate>>,
        TError,
        { id: string; data: KpUpdateDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof kpControllerUpdate>>,
    TError,
    { id: string; data: KpUpdateDto },
    TContext
> => {
    const mutationKey = ["kpControllerUpdate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof kpControllerUpdate>>,
        { id: string; data: KpUpdateDto }
    > = (props) => {
        const { id, data } = props ?? {};

        return kpControllerUpdate(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type KpControllerUpdateMutationResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerUpdate>>
>;
export type KpControllerUpdateMutationBody = KpUpdateDto;
export type KpControllerUpdateMutationError = void;

/**
 * @summary Обновить КП
 */
export const useKpControllerUpdate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof kpControllerUpdate>>,
            TError,
            { id: string; data: KpUpdateDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof kpControllerUpdate>>,
    TError,
    { id: string; data: KpUpdateDto },
    TContext
> => {
    return useMutation(
        getKpControllerUpdateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Удалить КП
 */
export type kpControllerDeleteResponse200 = {
    data: KpDto;
    status: 200;
};

export type kpControllerDeleteResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerDeleteResponse404 = {
    data: void;
    status: 404;
};

export type kpControllerDeleteResponseSuccess =
    kpControllerDeleteResponse200 & {
        headers: Headers;
    };
export type kpControllerDeleteResponseError = (
    | kpControllerDeleteResponse401
    | kpControllerDeleteResponse404
) & {
    headers: Headers;
};

export type kpControllerDeleteResponse =
    | kpControllerDeleteResponseSuccess
    | kpControllerDeleteResponseError;

export const getKpControllerDeleteUrl = (id: string) => {
    return `/api/admin/kp/${id}`;
};

export const kpControllerDelete = async (
    id: string,
    options?: RequestInit,
): Promise<kpControllerDeleteResponse> => {
    return customInstance<kpControllerDeleteResponse>(
        getKpControllerDeleteUrl(id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getKpControllerDeleteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof kpControllerDelete>>,
        TError,
        { id: string },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof kpControllerDelete>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["kpControllerDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof kpControllerDelete>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return kpControllerDelete(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type KpControllerDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerDelete>>
>;

export type KpControllerDeleteMutationError = void;

/**
 * @summary Удалить КП
 */
export const useKpControllerDelete = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof kpControllerDelete>>,
            TError,
            { id: string },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof kpControllerDelete>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(
        getKpControllerDeleteMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Загрузить смету
 */
export type kpControllerUploadEstimateResponse201 = {
    data: FileJson;
    status: 201;
};

export type kpControllerUploadEstimateResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerUploadEstimateResponse422 = {
    data: void;
    status: 422;
};

export type kpControllerUploadEstimateResponseSuccess =
    kpControllerUploadEstimateResponse201 & {
        headers: Headers;
    };
export type kpControllerUploadEstimateResponseError = (
    | kpControllerUploadEstimateResponse401
    | kpControllerUploadEstimateResponse422
) & {
    headers: Headers;
};

export type kpControllerUploadEstimateResponse =
    | kpControllerUploadEstimateResponseSuccess
    | kpControllerUploadEstimateResponseError;

export const getKpControllerUploadEstimateUrl = () => {
    return `/api/admin/kp/upload/estimate`;
};

export const kpControllerUploadEstimate = async (
    kpControllerUploadEstimateBody: KpControllerUploadEstimateBody,
    options?: RequestInit,
): Promise<kpControllerUploadEstimateResponse> => {
    const formData = new FormData();
    formData.append(`file`, kpControllerUploadEstimateBody.file);

    return customInstance<kpControllerUploadEstimateResponse>(
        getKpControllerUploadEstimateUrl(),
        {
            ...options,
            method: "POST",
            body: formData,
        },
    );
};

export const getKpControllerUploadEstimateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof kpControllerUploadEstimate>>,
        TError,
        { data: KpControllerUploadEstimateBody },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof kpControllerUploadEstimate>>,
    TError,
    { data: KpControllerUploadEstimateBody },
    TContext
> => {
    const mutationKey = ["kpControllerUploadEstimate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof kpControllerUploadEstimate>>,
        { data: KpControllerUploadEstimateBody }
    > = (props) => {
        const { data } = props ?? {};

        return kpControllerUploadEstimate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type KpControllerUploadEstimateMutationResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerUploadEstimate>>
>;
export type KpControllerUploadEstimateMutationBody =
    KpControllerUploadEstimateBody;
export type KpControllerUploadEstimateMutationError = void;

/**
 * @summary Загрузить смету
 */
export const useKpControllerUploadEstimate = <
    TError = void,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof kpControllerUploadEstimate>>,
            TError,
            { data: KpControllerUploadEstimateBody },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof kpControllerUploadEstimate>>,
    TError,
    { data: KpControllerUploadEstimateBody },
    TContext
> => {
    return useMutation(
        getKpControllerUploadEstimateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Загрузить документы
 */
export type kpControllerUploadDocumentsResponse201 = {
    data: FileJson[];
    status: 201;
};

export type kpControllerUploadDocumentsResponse401 = {
    data: void;
    status: 401;
};

export type kpControllerUploadDocumentsResponse422 = {
    data: void;
    status: 422;
};

export type kpControllerUploadDocumentsResponseSuccess =
    kpControllerUploadDocumentsResponse201 & {
        headers: Headers;
    };
export type kpControllerUploadDocumentsResponseError = (
    | kpControllerUploadDocumentsResponse401
    | kpControllerUploadDocumentsResponse422
) & {
    headers: Headers;
};

export type kpControllerUploadDocumentsResponse =
    | kpControllerUploadDocumentsResponseSuccess
    | kpControllerUploadDocumentsResponseError;

export const getKpControllerUploadDocumentsUrl = () => {
    return `/api/admin/kp/upload/documents`;
};

export const kpControllerUploadDocuments = async (
    kpControllerUploadDocumentsBody: KpControllerUploadDocumentsBody,
    options?: RequestInit,
): Promise<kpControllerUploadDocumentsResponse> => {
    const formData = new FormData();
    kpControllerUploadDocumentsBody.files.forEach((value) =>
        formData.append(`files`, value),
    );

    return customInstance<kpControllerUploadDocumentsResponse>(
        getKpControllerUploadDocumentsUrl(),
        {
            ...options,
            method: "POST",
            body: formData,
        },
    );
};

export const getKpControllerUploadDocumentsMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof kpControllerUploadDocuments>>,
        TError,
        { data: KpControllerUploadDocumentsBody },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof kpControllerUploadDocuments>>,
    TError,
    { data: KpControllerUploadDocumentsBody },
    TContext
> => {
    const mutationKey = ["kpControllerUploadDocuments"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof kpControllerUploadDocuments>>,
        { data: KpControllerUploadDocumentsBody }
    > = (props) => {
        const { data } = props ?? {};

        return kpControllerUploadDocuments(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type KpControllerUploadDocumentsMutationResult = NonNullable<
    Awaited<ReturnType<typeof kpControllerUploadDocuments>>
>;
export type KpControllerUploadDocumentsMutationBody =
    KpControllerUploadDocumentsBody;
export type KpControllerUploadDocumentsMutationError = void;

/**
 * @summary Загрузить документы
 */
export const useKpControllerUploadDocuments = <
    TError = void,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof kpControllerUploadDocuments>>,
            TError,
            { data: KpControllerUploadDocumentsBody },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof kpControllerUploadDocuments>>,
    TError,
    { data: KpControllerUploadDocumentsBody },
    TContext
> => {
    return useMutation(
        getKpControllerUploadDocumentsMutationOptions(options),
        queryClient,
    );
};
