/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Omnition Api Documentation
 * Документация Api для Omnition
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    ClientDto,
    CreateClientDto,
    UpdateClientDto,
} from "../../types/server";

import { customInstance } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить все папки клиентов
 */
export type clientControllerGetAllResponse200 = {
    data: ClientDto[];
    status: 200;
};

export type clientControllerGetAllResponse401 = {
    data: void;
    status: 401;
};

export type clientControllerGetAllResponseSuccess =
    clientControllerGetAllResponse200 & {
        headers: Headers;
    };
export type clientControllerGetAllResponseError =
    clientControllerGetAllResponse401 & {
        headers: Headers;
    };

export type clientControllerGetAllResponse =
    | clientControllerGetAllResponseSuccess
    | clientControllerGetAllResponseError;

export const getClientControllerGetAllUrl = () => {
    return `/api/admin/client`;
};

export const clientControllerGetAll = async (
    options?: RequestInit,
): Promise<clientControllerGetAllResponse> => {
    return customInstance<clientControllerGetAllResponse>(
        getClientControllerGetAllUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getClientControllerGetAllQueryKey = () => {
    return [`/api/admin/client`] as const;
};

export const getClientControllerGetAllQueryOptions = <
    TData = Awaited<ReturnType<typeof clientControllerGetAll>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof clientControllerGetAll>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getClientControllerGetAllQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof clientControllerGetAll>>
    > = ({ signal }) => clientControllerGetAll({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof clientControllerGetAll>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClientControllerGetAllQueryResult = NonNullable<
    Awaited<ReturnType<typeof clientControllerGetAll>>
>;
export type ClientControllerGetAllQueryError = void;

export function useClientControllerGetAll<
    TData = Awaited<ReturnType<typeof clientControllerGetAll>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof clientControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof clientControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useClientControllerGetAll<
    TData = Awaited<ReturnType<typeof clientControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerGetAll>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof clientControllerGetAll>>,
                    TError,
                    Awaited<ReturnType<typeof clientControllerGetAll>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useClientControllerGetAll<
    TData = Awaited<ReturnType<typeof clientControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить все папки клиентов
 */

export function useClientControllerGetAll<
    TData = Awaited<ReturnType<typeof clientControllerGetAll>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerGetAll>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getClientControllerGetAllQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Создать папку клиента
 */
export type clientControllerCreateResponse201 = {
    data: ClientDto;
    status: 201;
};

export type clientControllerCreateResponse400 = {
    data: void;
    status: 400;
};

export type clientControllerCreateResponse401 = {
    data: void;
    status: 401;
};

export type clientControllerCreateResponseSuccess =
    clientControllerCreateResponse201 & {
        headers: Headers;
    };
export type clientControllerCreateResponseError = (
    | clientControllerCreateResponse400
    | clientControllerCreateResponse401
) & {
    headers: Headers;
};

export type clientControllerCreateResponse =
    | clientControllerCreateResponseSuccess
    | clientControllerCreateResponseError;

export const getClientControllerCreateUrl = () => {
    return `/api/admin/client`;
};

export const clientControllerCreate = async (
    createClientDto: CreateClientDto,
    options?: RequestInit,
): Promise<clientControllerCreateResponse> => {
    return customInstance<clientControllerCreateResponse>(
        getClientControllerCreateUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(createClientDto),
        },
    );
};

export const getClientControllerCreateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof clientControllerCreate>>,
        TError,
        { data: CreateClientDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof clientControllerCreate>>,
    TError,
    { data: CreateClientDto },
    TContext
> => {
    const mutationKey = ["clientControllerCreate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof clientControllerCreate>>,
        { data: CreateClientDto }
    > = (props) => {
        const { data } = props ?? {};

        return clientControllerCreate(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ClientControllerCreateMutationResult = NonNullable<
    Awaited<ReturnType<typeof clientControllerCreate>>
>;
export type ClientControllerCreateMutationBody = CreateClientDto;
export type ClientControllerCreateMutationError = void;

/**
 * @summary Создать папку клиента
 */
export const useClientControllerCreate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof clientControllerCreate>>,
            TError,
            { data: CreateClientDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof clientControllerCreate>>,
    TError,
    { data: CreateClientDto },
    TContext
> => {
    return useMutation(
        getClientControllerCreateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Получить папку клиента по ID
 */
export type clientControllerFindByIdResponse200 = {
    data: ClientDto;
    status: 200;
};

export type clientControllerFindByIdResponse401 = {
    data: void;
    status: 401;
};

export type clientControllerFindByIdResponse404 = {
    data: void;
    status: 404;
};

export type clientControllerFindByIdResponseSuccess =
    clientControllerFindByIdResponse200 & {
        headers: Headers;
    };
export type clientControllerFindByIdResponseError = (
    | clientControllerFindByIdResponse401
    | clientControllerFindByIdResponse404
) & {
    headers: Headers;
};

export type clientControllerFindByIdResponse =
    | clientControllerFindByIdResponseSuccess
    | clientControllerFindByIdResponseError;

export const getClientControllerFindByIdUrl = (id: number) => {
    return `/api/admin/client/${id}`;
};

export const clientControllerFindById = async (
    id: number,
    options?: RequestInit,
): Promise<clientControllerFindByIdResponse> => {
    return customInstance<clientControllerFindByIdResponse>(
        getClientControllerFindByIdUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getClientControllerFindByIdQueryKey = (id: number) => {
    return [`/api/admin/client/${id}`] as const;
};

export const getClientControllerFindByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof clientControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getClientControllerFindByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof clientControllerFindById>>
    > = ({ signal }) =>
        clientControllerFindById(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof clientControllerFindById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClientControllerFindByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof clientControllerFindById>>
>;
export type ClientControllerFindByIdQueryError = void;

export function useClientControllerFindById<
    TData = Awaited<ReturnType<typeof clientControllerFindById>>,
    TError = void,
>(
    id: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof clientControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof clientControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useClientControllerFindById<
    TData = Awaited<ReturnType<typeof clientControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerFindById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof clientControllerFindById>>,
                    TError,
                    Awaited<ReturnType<typeof clientControllerFindById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useClientControllerFindById<
    TData = Awaited<ReturnType<typeof clientControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить папку клиента по ID
 */

export function useClientControllerFindById<
    TData = Awaited<ReturnType<typeof clientControllerFindById>>,
    TError = void,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof clientControllerFindById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getClientControllerFindByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить папку клиента
 */
export type clientControllerUpdateResponse200 = {
    data: ClientDto;
    status: 200;
};

export type clientControllerUpdateResponse401 = {
    data: void;
    status: 401;
};

export type clientControllerUpdateResponse404 = {
    data: void;
    status: 404;
};

export type clientControllerUpdateResponseSuccess =
    clientControllerUpdateResponse200 & {
        headers: Headers;
    };
export type clientControllerUpdateResponseError = (
    | clientControllerUpdateResponse401
    | clientControllerUpdateResponse404
) & {
    headers: Headers;
};

export type clientControllerUpdateResponse =
    | clientControllerUpdateResponseSuccess
    | clientControllerUpdateResponseError;

export const getClientControllerUpdateUrl = (id: number) => {
    return `/api/admin/client/${id}`;
};

export const clientControllerUpdate = async (
    id: number,
    updateClientDto: UpdateClientDto,
    options?: RequestInit,
): Promise<clientControllerUpdateResponse> => {
    return customInstance<clientControllerUpdateResponse>(
        getClientControllerUpdateUrl(id),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateClientDto),
        },
    );
};

export const getClientControllerUpdateMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof clientControllerUpdate>>,
        TError,
        { id: number; data: UpdateClientDto },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof clientControllerUpdate>>,
    TError,
    { id: number; data: UpdateClientDto },
    TContext
> => {
    const mutationKey = ["clientControllerUpdate"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof clientControllerUpdate>>,
        { id: number; data: UpdateClientDto }
    > = (props) => {
        const { id, data } = props ?? {};

        return clientControllerUpdate(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ClientControllerUpdateMutationResult = NonNullable<
    Awaited<ReturnType<typeof clientControllerUpdate>>
>;
export type ClientControllerUpdateMutationBody = UpdateClientDto;
export type ClientControllerUpdateMutationError = void;

/**
 * @summary Обновить папку клиента
 */
export const useClientControllerUpdate = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof clientControllerUpdate>>,
            TError,
            { id: number; data: UpdateClientDto },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof clientControllerUpdate>>,
    TError,
    { id: number; data: UpdateClientDto },
    TContext
> => {
    return useMutation(
        getClientControllerUpdateMutationOptions(options),
        queryClient,
    );
};
/**
 * @summary Удалить папку клиента
 */
export type clientControllerDeleteResponse200 = {
    data: ClientDto;
    status: 200;
};

export type clientControllerDeleteResponse401 = {
    data: void;
    status: 401;
};

export type clientControllerDeleteResponse404 = {
    data: void;
    status: 404;
};

export type clientControllerDeleteResponseSuccess =
    clientControllerDeleteResponse200 & {
        headers: Headers;
    };
export type clientControllerDeleteResponseError = (
    | clientControllerDeleteResponse401
    | clientControllerDeleteResponse404
) & {
    headers: Headers;
};

export type clientControllerDeleteResponse =
    | clientControllerDeleteResponseSuccess
    | clientControllerDeleteResponseError;

export const getClientControllerDeleteUrl = (id: number) => {
    return `/api/admin/client/${id}`;
};

export const clientControllerDelete = async (
    id: number,
    options?: RequestInit,
): Promise<clientControllerDeleteResponse> => {
    return customInstance<clientControllerDeleteResponse>(
        getClientControllerDeleteUrl(id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getClientControllerDeleteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof clientControllerDelete>>,
        TError,
        { id: number },
        TContext
    >;
    request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof clientControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["clientControllerDelete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof clientControllerDelete>>,
        { id: number }
    > = (props) => {
        const { id } = props ?? {};

        return clientControllerDelete(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ClientControllerDeleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof clientControllerDelete>>
>;

export type ClientControllerDeleteMutationError = void;

/**
 * @summary Удалить папку клиента
 */
export const useClientControllerDelete = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof clientControllerDelete>>,
            TError,
            { id: number },
            TContext
        >;
        request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof clientControllerDelete>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getClientControllerDeleteMutationOptions(options),
        queryClient,
    );
};
